version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./src:/var/www/html
    ports: 
      - 9000:80

  mariadb:
    image: mariadb:10.8
    restart: always
    ports:
      - "3308:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1

  phpmyadmin:
    image: phpmyadmin:5.2
    restart: always
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1